In [1]:
import numpy as np

In [5]:
prices = [54.32, 56, 58.93, 57.34]
prices = np.array(prices, dtype=np.float32)
prices.dtype

dtype('float32')

In [6]:
print(np.zeros(5))
print(np.ones(10))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [8]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print(np.arange(2,11,2))

[ 2  4  6  8 10]


linspace has an inclusive upper and lower bound and the 3rd parameter divides the space evenly between that many numbers

effectively does (2nd param - 1st param) / (3rd param - 1) to get the interval between each of the values

In [11]:
print(np.linspace(1,9,5))

[1. 3. 5. 7. 9.]


In [12]:
print(np.linspace(1,10,7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


## Array functions
#### Fetch functions

In [14]:
prices

array([54.32, 56.  , 58.93, 57.34], dtype=float32)

In [17]:
prices[0]

54.32

In [18]:
prices[0:3]

array([54.32, 56.  , 58.93], dtype=float32)

In [19]:
prices[0:9]

array([54.32, 56.  , 58.93, 57.34], dtype=float32)

In [20]:
prices.item(1)

56.0

In [22]:
print(prices.min())
print(prices.max())
print(prices.mean())

54.32
58.93
56.6475


In [23]:
print(prices.argmax())
print(prices.argmin())

2
0


In [25]:
print(prices.shape)
print(prices.size)

(4,)
4


In [26]:
print(prices.dtype)

float32


#### Modification functions

In [27]:
prices

array([54.32, 56.  , 58.93, 57.34], dtype=float32)

In [28]:
prices[1] = 57.01
prices

array([54.32, 57.01, 58.93, 57.34], dtype=float32)

In [31]:
print(prices.tolist())
print(type(prices.tolist()))
print(prices)
print(type(prices))

[54.31999969482422, 57.0099983215332, 58.93000030517578, 57.34000015258789]
<class 'list'>
[54.32 57.01 58.93 57.34]
<class 'numpy.ndarray'>


In [35]:
prices.sort(kind='quicksort') # modifies array
prices

array([54.32, 57.01, 57.34, 58.93], dtype=float32)

In [36]:
doubled_prices = prices * 2
doubled_prices

array([108.64, 114.02, 114.68, 117.86], dtype=float32)

In [37]:
prices

array([54.32, 57.01, 57.34, 58.93], dtype=float32)

In [38]:
added_prices = prices + 10
added_prices

array([64.32    , 67.009995, 67.34    , 68.93    ], dtype=float32)

In [40]:
new_prices = np.array([100, 100, 100, 100])

In [41]:
final_prices = new_prices + prices # vector operation
final_prices

array([154.31999969, 157.00999832, 157.34000015, 158.93000031])